remote_theme: fongandrew/hydeout
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            exterior
description:      'ya nadie se acuerda de lo que quer√≠a ser'
url:              https://infrahumano.github.io/exterior
sidebar_home_link: false

author:
  name:           'javier moreno'
  url:            https://twitter.com/infrahumano

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
